export const OPS_TAXONOMY_CATALOG = {
  schemaVersion: "ops-taxonomy/v1",
  generatedAt: "2026-04-20T00:00:00.000Z",
  errorEnvelope: {
    contractVersion: "tool-error/v2",
    contextIds: "traceId/requestId pair is included on structured error payloads for direct tools and workflow failures.",
  },
  summary: [
    "Machine-readable operations taxonomy for error handling, severity, and retry guidance.",
    "Use this with sg://runtime and sg://benchmarks to build predictable operational behavior.",
  ],
  severities: [
    {
      level: "low",
      meaning: "Non-critical input or contract issue. Caller can typically recover immediately.",
      escalation: "No pager alert. Surface actionable validation hints to the caller.",
    },
    {
      level: "medium",
      meaning: "Recoverable runtime failure or transient upstream instability.",
      escalation: "Warn-level telemetry and retry policy should apply.",
    },
    {
      level: "high",
      meaning: "Critical failure mode requiring operator attention or dependency intervention.",
      escalation: "Error-level telemetry and incident triage.",
    },
  ],
  errorCodes: [
    {
      code: "VALIDATION_ERROR",
      source: "validation",
      retryable: false,
      severity: "low",
      statusCode: 400,
      category: "client_input",
      suggestedAction: "Fix parameters against the tool schema and retry.",
    },
    {
      code: "WORKFLOW_DEPENDENCY_ERROR",
      source: "planner",
      retryable: false,
      severity: "low",
      statusCode: 422,
      category: "workflow_dependency",
      suggestedAction: "Run the prerequisite tool step first, then continue the workflow.",
    },
    {
      code: "TOOL_RESULT_ERROR",
      source: "query",
      retryable: true,
      severity: "medium",
      statusCode: 502,
      category: "workflow_execution",
      suggestedAction: "Inspect failedStep details and retry only after fixing the upstream input or dependency.",
    },
    {
      code: "AUTH_MISSING",
      source: "LTA",
      retryable: false,
      severity: "high",
      statusCode: 401,
      category: "credential_configuration",
      suggestedAction: "Set the required credential in env or keystore and rerun.",
    },
    {
      code: "TIMEOUT",
      source: "http-client",
      retryable: true,
      severity: "medium",
      statusCode: 408,
      category: "upstream_timeout",
      suggestedAction: "Retry later or increase timeout for the impacted API family.",
    },
    {
      code: "NETWORK_ERROR",
      source: "http-client",
      retryable: true,
      severity: "medium",
      statusCode: 503,
      category: "network_path",
      suggestedAction: "Check network reachability and upstream status, then retry.",
    },
    {
      code: "RETRY_EXHAUSTED",
      source: "http-client",
      retryable: true,
      severity: "high",
      statusCode: 503,
      category: "upstream_reliability",
      suggestedAction: "Escalate to operator workflow if repeated over multiple attempts.",
    },
    {
      code: "RESOURCE_ID_REQUIRED",
      source: "data.gov.sg",
      retryable: false,
      severity: "low",
      statusCode: 400,
      category: "dataset_contract",
      suggestedAction: "Provide a machine-readable resourceId from sg_datagov_resources.",
    },
    {
      code: "RESOURCE_NOT_MACHINE_READABLE",
      source: "data.gov.sg",
      retryable: false,
      severity: "low",
      statusCode: 422,
      category: "dataset_contract",
      suggestedAction: "Choose a CSV/GeoJSON/JSON resource before running row reads.",
    },
    {
      code: "EMPTY_RESULT",
      source: "NEA",
      retryable: false,
      severity: "low",
      statusCode: 404,
      category: "workflow_dependency",
      suggestedAction: "Broaden or remove optional filters and retry.",
    },
    {
      code: "TRANSIT_TRACE_NOT_FOUND",
      source: "sg_transit_policy_replay",
      retryable: false,
      severity: "low",
      statusCode: 404,
      category: "workflow_dependency",
      suggestedAction: "Call sg_transit_policy_audit first and pass a valid traceId.",
    },
    {
      code: "HTTP_429",
      source: "upstream",
      retryable: true,
      severity: "medium",
      statusCode: 429,
      category: "upstream_reliability",
      suggestedAction: "Respect retry-after guidance or reduce request rate before retrying.",
    },
    {
      code: "HTTP_4XX",
      source: "upstream",
      retryable: false,
      severity: "low",
      statusCode: 400,
      category: "client_input",
      suggestedAction: "Validate request parameters and upstream contract assumptions before retrying.",
    },
    {
      code: "HTTP_5XX",
      source: "upstream",
      retryable: true,
      severity: "high",
      statusCode: 503,
      category: "upstream_reliability",
      suggestedAction: "Retry with backoff and escalate if repeated across multiple attempts.",
    },
    {
      code: "INTERNAL_ERROR",
      source: "internal",
      retryable: false,
      severity: "high",
      statusCode: 500,
      category: "server_fault",
      suggestedAction: "Check server logs and trace/request IDs before retrying.",
    },
  ],
} as const;
