name = "Catppuccin Mocha"
background = "#1e1e2e"
foreground = "#cdd6f4"
cursor = "#f5e0dc"
vi_cursor_color = "#f9e2af"
selection = "#585b7080"
opacity = 1.0
font_family = "Monaspace Neon"
chrome_font_family = "IBM Plex Mono"
font_size = 24.0
tab_bar_bg = "#181825"
tab_active_bg = "#313244"
tab_inactive_bg = "#1e1e2e"
tab_text = "#cdd6f4"
status_bar_bg = "#181825"
status_bar_text = "#bac2de"
input_bg = "#24273a"
input_text = "#cdd6f4"
block_separator = "#45475a"
block_success_accent = "#a6e3a1"
block_error_accent = "#f38ba8"
highlight_match = "#f9e2af55"
highlight_current_match = "#fab38780"
hyperlink_color = "#89b4fa"
bracket_match = "#94e2d566"

[ansi]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#94e2d5"
white = "#bac2de"
bright_black = "#585b70"
bright_red = "#eba0ac"
bright_green = "#a6e3a1"
bright_yellow = "#f9e2af"
bright_blue = "#89b4fa"
bright_magenta = "#cba6f7"
bright_cyan = "#94e2d5"
bright_white = "#cdd6f4"

[syntax]
command = "#89b4fa"
argument = "#cdd6f4"
flag = "#cba6f7"
path = "#a6e3a1"
string = "#a6e3a1"
number = "#fab387"
pipe = "#6c7086"
redirect = "#6c7086"
variable = "#f9e2af"
comment = "#6c7086"
error = "#f38ba8"
