name = "Gruvbox Wok Neon"
background = "#090a12"
foreground = "#edf7ff"
cursor = "#00ffd0"
vi_cursor_color = "#ffd166"
selection = "#334cff55"
opacity = 1.0
font_family = "JetBrainsMono Nerd Font Mono"
chrome_font_family = "JetBrainsMono Nerd Font Mono"
font_size = 24.0
tab_bar_bg = "#05060c"
tab_active_bg = "#151a31"
tab_inactive_bg = "#0d1020"
tab_text = "#edf7ff"
status_bar_bg = "#05060c"
status_bar_text = "#8792b4"
input_bg = "#101528"
input_text = "#edf7ff"
block_separator = "#26304f"
block_success_accent = "#00ffd0"
block_error_accent = "#ff4d7d"
highlight_match = "#ffd16655"
highlight_current_match = "#ff8a3d80"
hyperlink_color = "#6da8ff"
bracket_match = "#00ffd055"

[ansi]
black = "#090a12"
red = "#ff4d7d"
green = "#00ffd0"
yellow = "#ffd166"
blue = "#6da8ff"
magenta = "#df75ff"
cyan = "#26f0ff"
white = "#edf7ff"
bright_black = "#59617e"
bright_red = "#ff7098"
bright_green = "#5effdc"
bright_yellow = "#ffe08f"
bright_blue = "#96c2ff"
bright_magenta = "#eca3ff"
bright_cyan = "#74f6ff"
bright_white = "#ffffff"

[syntax]
command = "#6da8ff"
argument = "#edf7ff"
flag = "#df75ff"
path = "#00ffd0"
string = "#9eff6e"
number = "#ff8a3d"
pipe = "#8792b4"
redirect = "#8792b4"
variable = "#ffd166"
comment = "#59617e"
error = "#ff4d7d"
