name = "Gruvbox Dark"
background = "#282828"
foreground = "#ebdbb2"
cursor = "#fabd2f"
vi_cursor_color = "#d3869b"
selection = "#665c5488"
opacity = 1.0
font_family = "JetBrainsMono Nerd Font Mono"
chrome_font_family = "JetBrainsMono Nerd Font Mono"
font_size = 24.0
tab_bar_bg = "#1d2021"
tab_active_bg = "#3c3836"
tab_inactive_bg = "#282828"
tab_text = "#ebdbb2"
status_bar_bg = "#1d2021"
status_bar_text = "#b8bb26"
input_bg = "#32302f"
input_text = "#fbf1c7"
block_separator = "#504945"
block_success_accent = "#b8bb26"
block_error_accent = "#fb4934"
highlight_match = "#fabd2f55"
highlight_current_match = "#fe801980"
hyperlink_color = "#83a598"
bracket_match = "#8ec07c66"

[ansi]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
bright_black = "#928374"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
bright_cyan = "#8ec07c"
bright_white = "#ebdbb2"

[syntax]
command = "#83a598"
argument = "#ebdbb2"
flag = "#d3869b"
path = "#b8bb26"
string = "#b8bb26"
number = "#fe8019"
pipe = "#928374"
redirect = "#928374"
variable = "#fabd2f"
comment = "#928374"
error = "#fb4934"
