name = "Gruvbox Wok Day"
background = "#f6f3ec"
foreground = "#182126"
cursor = "#007a71"
vi_cursor_color = "#a05a00"
selection = "#8cc7d966"
opacity = 1.0
font_family = "JetBrainsMono Nerd Font Mono"
chrome_font_family = "JetBrainsMono Nerd Font Mono"
font_size = 24.0
tab_bar_bg = "#ebe6dc"
tab_active_bg = "#ffffff"
tab_inactive_bg = "#ded8cd"
tab_text = "#182126"
status_bar_bg = "#ebe6dc"
status_bar_text = "#5d686d"
input_bg = "#fffdf8"
input_text = "#182126"
block_separator = "#c7d0d0"
block_success_accent = "#007a71"
block_error_accent = "#c33846"
highlight_match = "#e4b64066"
highlight_current_match = "#d9792f80"
hyperlink_color = "#255fba"
bracket_match = "#007a7155"

[ansi]
black = "#182126"
red = "#c33846"
green = "#007a71"
yellow = "#a05a00"
blue = "#255fba"
magenta = "#8951b5"
cyan = "#168189"
white = "#f6f3ec"
bright_black = "#6a7478"
bright_red = "#df5360"
bright_green = "#009985"
bright_yellow = "#bd7417"
bright_blue = "#3c76d3"
bright_magenta = "#a66bd0"
bright_cyan = "#2d9ca3"
bright_white = "#ffffff"

[syntax]
command = "#255fba"
argument = "#182126"
flag = "#8951b5"
path = "#007a71"
string = "#5f8a00"
number = "#bd7417"
pipe = "#7a8589"
redirect = "#7a8589"
variable = "#a05a00"
comment = "#8a9497"
error = "#c33846"
