name = "Solarized Dark"
background = "#002b36"
foreground = "#839496"
cursor = "#93a1a1"
vi_cursor_color = "#b58900"
selection = "#073642cc"
opacity = 1.0
font_family = "JetBrains Mono"
chrome_font_family = "IBM Plex Mono"
font_size = 24.0
tab_bar_bg = "#00212a"
tab_active_bg = "#073642"
tab_inactive_bg = "#002b36"
tab_text = "#93a1a1"
status_bar_bg = "#00212a"
status_bar_text = "#2aa198"
input_bg = "#073642"
input_text = "#93a1a1"
block_separator = "#0d4858"
block_success_accent = "#859900"
block_error_accent = "#dc322f"
highlight_match = "#b5890055"
highlight_current_match = "#cb4b1680"
hyperlink_color = "#268bd2"
bracket_match = "#2aa19866"

[ansi]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"
bright_black = "#002b36"
bright_red = "#cb4b16"
bright_green = "#586e75"
bright_yellow = "#657b83"
bright_blue = "#839496"
bright_magenta = "#6c71c4"
bright_cyan = "#93a1a1"
bright_white = "#fdf6e3"

[syntax]
command = "#268bd2"
argument = "#93a1a1"
flag = "#6c71c4"
path = "#859900"
string = "#2aa198"
number = "#cb4b16"
pipe = "#586e75"
redirect = "#586e75"
variable = "#b58900"
comment = "#586e75"
error = "#dc322f"
