-- poor-cli/commands.lua
-- Vim commands for poor-cli

local M = {}

local function create_command(name, fn, opts)
    pcall(vim.api.nvim_del_user_command, name)
    vim.api.nvim_create_user_command(name, fn, opts or {})
end

local function open_scratch(title, content, filetype)
    local buf = vim.api.nvim_create_buf(false, true)
    vim.bo[buf].buftype = "nofile"
    vim.bo[buf].bufhidden = "wipe"
    vim.bo[buf].swapfile = false
    vim.bo[buf].filetype = filetype or "markdown"
    vim.api.nvim_buf_set_name(buf, title)
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.split(content, "\n", { plain = true }))
    vim.cmd("botright split")
    vim.api.nvim_win_set_buf(0, buf)
    return buf
end

local function build_status_text()
    local rpc = require("poor-cli.rpc")
    local inline = require("poor-cli.inline")

    local rpc_status = rpc.get_status()
    local inline_status = inline.get_status()
    local enabled, reason = inline.is_enabled_for_buffer(0, { manual = false })
    local provider_name = "unknown"
    local provider_model = "unknown"
    local provider_info = rpc_status.provider_info or {}
    if type(provider_info) == "table" then
        provider_name = provider_info.name or provider_name
        provider_model = provider_info.model or provider_model
    end

    local lines = {
        "Server state: " .. tostring(rpc_status.state),
        "Running: " .. tostring(rpc_status.running),
        "Initialized: " .. tostring(rpc_status.initialized),
        "Provider: " .. provider_name,
        "Model: " .. provider_model,
        "Log path: " .. tostring(rpc_status.log_path or ""),
        "Completion state: " .. tostring(inline_status.state),
        "Completion enabled in buffer: " .. tostring(enabled),
    }

    if not enabled and reason ~= "" then
        table.insert(lines, "Completion disabled reason: " .. reason)
    end

    local multiplayer = rpc_status.multiplayer or {}
    if multiplayer.enabled then
        table.insert(lines, "Room: " .. tostring(multiplayer.room or ""))
        table.insert(lines, "Role: " .. tostring(multiplayer.role or ""))
        table.insert(lines, "Members: " .. tostring(multiplayer.member_count or 0))
        table.insert(lines, "Queue: " .. tostring(multiplayer.queue_depth or 0))
    end

    local capabilities = rpc_status.capabilities
    local guarded = capabilities and capabilities.guardedFlow or nil
    if type(guarded) == "table" then
        table.insert(lines, "Plan review: " .. tostring(guarded.planReview == true))
        table.insert(lines, "Permission review: " .. tostring(guarded.permissionRequests == true))
    end

    local security = capabilities and capabilities.security or nil
    if type(security) == "table" then
        table.insert(lines, "Trusted workspace: " .. tostring(security.trustedWorkspaceBoundary == true))
    end

    if rpc_status.last_error_message and rpc_status.last_error_message ~= "" then
        table.insert(lines, "Last error: " .. rpc_status.last_error_message)
    end

    if rpc_status.last_stderr_excerpt and rpc_status.last_stderr_excerpt ~= "" then
        table.insert(lines, "")
        table.insert(lines, "Recent stderr:")
        table.insert(lines, rpc_status.last_stderr_excerpt)
    end

    return table.concat(lines, "\n")
end

local function copy_to_clipboard(text)
    local ok = pcall(vim.fn.setreg, "+", text)
    if ok then
        return true
    end
    vim.fn.setreg('"', text)
    return false
end

local function write_min_init(path)
    local config = require("poor-cli.config")
    local plugin_file = vim.api.nvim_get_runtime_file("lua/poor-cli/init.lua", false)[1] or ""
    local plugin_root = plugin_file ~= "" and vim.fn.fnamemodify(plugin_file, ":h:h:h") or vim.fn.getcwd()
    local lines = {
        "-- Generated by :PoorCliWriteMinInit",
        "vim.opt.runtimepath:prepend(" .. string.format("%q", plugin_root) .. ")",
        "require('poor-cli').setup({",
        "  auto_start = true,",
        "  debug = true,",
        "  check_health_on_setup = true,",
        "})",
    }
    vim.fn.writefile(lines, path)
    return path
end

function M.setup()
    local rpc = require("poor-cli.rpc")
    local chat = require("poor-cli.chat")
    local inline = require("poor-cli.inline")
    local diagnostics = require("poor-cli.diagnostics")
    local telescope = require("poor-cli.telescope")

    create_command("PoorCliStart", function()
        if rpc.start() then
            rpc.initialize(function(_result, err)
                if not err then
                    vim.notify("[poor-cli] Initialized", vim.log.levels.INFO)
                end
            end)
        end
    end, { desc = "Start poor-cli server" })

    create_command("PoorCliStop", function()
        rpc.stop()
    end, { desc = "Stop poor-cli server" })

    create_command("PoorCliRestart", function()
        rpc.restart(function(_result, err)
            if err then
                vim.notify("[poor-cli] Restart failed: " .. vim.inspect(err), vim.log.levels.ERROR)
            else
                vim.notify("[poor-cli] Restarted", vim.log.levels.INFO)
            end
        end)
    end, { desc = "Restart poor-cli server" })

    create_command("PoorCliCancel", function()
        local cancelled_inline = inline.cancel_active_request()
        local cancelled_chat = chat.cancel_active_stream("Cancelled from :PoorCliCancel.")
        if not cancelled_inline and not cancelled_chat then
            vim.notify("[poor-cli] No active poor-cli request", vim.log.levels.INFO)
        end
    end, { desc = "Cancel active poor-cli requests" })

    create_command("PoorCliChat", function()
        chat.toggle()
    end, { desc = "Toggle poor-cli chat panel" })

    create_command("PoorCliSend", function(opts)
        if opts.args and opts.args ~= "" then
            chat.open()
            chat.send(opts.args)
        else
            chat.prompt_and_send()
        end
    end, { nargs = "*", desc = "Send message to poor-cli" })

    create_command("PoorCliClear", function()
        chat.clear()
    end, { desc = "Clear chat history" })

    create_command("PoorCliDiagnostics", function()
        diagnostics.toggle()
    end, { desc = "Toggle poor-cli inline diagnostics" })

    create_command("PoorCliCheckpoints", function()
        telescope.open_checkpoints_picker()
    end, { desc = "Browse/restore checkpoints with Telescope" })

    create_command("PoorCliComplete", function()
        inline.trigger({ manual = true })
    end, { desc = "Trigger inline completion" })

    create_command("PoorCliAccept", function()
        inline.accept()
    end, { desc = "Accept inline completion" })

    create_command("PoorCliDismiss", function()
        inline.dismiss()
    end, { desc = "Dismiss inline completion" })

    create_command("PoorCliSwitchProvider", function(opts)
        local args = vim.split(opts.args, " ")
        local provider = args[1]
        local model = args[2]

        if not provider or provider == "" then
            vim.ui.select({ "gemini", "openai", "anthropic", "ollama" }, {
                prompt = "Select provider:",
            }, function(choice)
                if choice then
                    rpc.request("poor-cli/switchProvider", {
                        provider = choice,
                    }, function(_result, err)
                        if err then
                            vim.notify("[poor-cli] Switch failed: " .. vim.inspect(err), vim.log.levels.ERROR)
                        else
                            vim.notify("[poor-cli] Switched to " .. choice, vim.log.levels.INFO)
                        end
                    end)
                end
            end)
            return
        end

        rpc.request("poor-cli/switchProvider", {
            provider = provider,
            model = model,
        }, function(_result, err)
            vim.schedule(function()
                if err then
                    vim.notify("[poor-cli] Switch failed: " .. vim.inspect(err), vim.log.levels.ERROR)
                else
                    vim.notify("[poor-cli] Switched to " .. provider, vim.log.levels.INFO)
                end
            end)
        end)
    end, { nargs = "*", desc = "Switch AI provider" })

    create_command("PoorCliStatus", function()
        vim.notify("[poor-cli]\n" .. build_status_text(), vim.log.levels.INFO)
    end, { desc = "Show poor-cli status" })

    create_command("PoorCliDoctor", function()
        local report = rpc.build_debug_report({
            {
                title = "Status",
                body = build_status_text(),
            },
        })
        open_scratch("[poor-cli doctor]", report, "markdown")
    end, { desc = "Open poor-cli diagnostic report" })

    create_command("PoorCliCopyDebugInfo", function()
        local report = rpc.build_debug_report({
            {
                title = "Status",
                body = build_status_text(),
            },
        })
        local copied = copy_to_clipboard(report)
        vim.notify(
            copied and "[poor-cli] Debug info copied to clipboard" or "[poor-cli] Debug info copied to unnamed register",
            vim.log.levels.INFO
        )
    end, { desc = "Copy poor-cli debug report" })

    create_command("PoorCliOpenLog", function()
        vim.cmd("edit " .. vim.fn.fnameescape(rpc.get_log_path()))
    end, { desc = "Open poor-cli server log" })

    create_command("PoorCliOpenStateDir", function()
        local dir = require("poor-cli.config").get_state_dir()
        vim.cmd("edit " .. vim.fn.fnameescape(dir))
    end, { desc = "Open poor-cli state directory" })

    create_command("PoorCliWriteMinInit", function(opts)
        local path = opts.args ~= "" and vim.fn.fnamemodify(opts.args, ":p")
            or vim.fs.joinpath(require("poor-cli.config").get_state_dir(), "poor-cli-minimal-init.lua")
        local written = write_min_init(path)
        vim.notify("[poor-cli] Wrote minimal init to " .. written, vim.log.levels.INFO)
    end, { nargs = "?", desc = "Write a minimal init.lua for poor-cli bug reports" })

    create_command("PoorCliExplain", function(opts)
        M.explain_code(opts.range, opts.line1, opts.line2)
    end, { range = true, desc = "Explain selected code" })

    create_command("PoorCliRefactor", function(opts)
        M.refactor_code(opts.range, opts.line1, opts.line2)
    end, { range = true, desc = "Refactor selected code" })

    create_command("PoorCliTest", function()
        M.generate_tests()
    end, { desc = "Generate tests for current function" })

    create_command("PoorCliDoc", function()
        M.generate_docs()
    end, { desc = "Generate documentation for current function" })

    create_command("PoorCliFixDiagnostics", function()
        local lsp = require("poor-cli.lsp")
        lsp.fix_diagnostics()
    end, { desc = "Fix LSP diagnostics with AI" })

    create_command("PoorCliAutoTrigger", function()
        local cfg = require("poor-cli.config")
        local current = cfg.get("auto_trigger")
        cfg.config.auto_trigger = not current
        if cfg.config.auto_trigger then
            local augroup = vim.api.nvim_create_augroup("poor-cli-auto-trigger", { clear = true })
            vim.api.nvim_create_autocmd("TextChangedI", {
                group = augroup,
                callback = function()
                    if rpc.is_running() then
                        inline.auto_trigger()
                    end
                end,
            })
            vim.notify("[poor-cli] Auto-trigger ON", vim.log.levels.INFO)
        else
            vim.api.nvim_create_augroup("poor-cli-auto-trigger", { clear = true })
            inline.cancel_auto_trigger()
            vim.notify("[poor-cli] Auto-trigger OFF", vim.log.levels.INFO)
        end
    end, { desc = "Toggle auto-trigger for inline completion" })

    create_command("PoorCliAcceptWord", function()
        inline.accept_word()
    end, { desc = "Accept next word of inline completion" })

    create_command("PoorCliAcceptLine", function()
        inline.accept_line()
    end, { desc = "Accept current line of inline completion" })
end

function M.explain_code(range, line1, line2)
    local rpc = require("poor-cli.rpc")
    local chat = require("poor-cli.chat")

    local lines
    if range > 0 then
        lines = vim.api.nvim_buf_get_lines(0, line1 - 1, line2, false)
    else
        lines = { vim.api.nvim_get_current_line() }
    end

    local code = table.concat(lines, "\n")
    local language = vim.bo.filetype

    chat.open()
    rpc.request("poor-cli/chat", {
        message = "Please explain this " .. language .. " code:\n\n```" .. language .. "\n" .. code .. "\n```",
    }, function(result, err)
        vim.schedule(function()
            if err then
                chat.append_message("assistant", "Error: " .. vim.inspect(err))
            elseif result and result.content then
                chat.append_message("user", "Explain:\n```" .. language .. "\n" .. code .. "\n```")
                chat.append_message("assistant", result.content)
            end
        end)
    end)
end

function M.refactor_code(range, line1, line2)
    local rpc = require("poor-cli.rpc")

    local lines
    if range > 0 then
        lines = vim.api.nvim_buf_get_lines(0, line1 - 1, line2, false)
    else
        vim.notify("[poor-cli] Select code to refactor", vim.log.levels.WARN)
        return
    end

    local code = table.concat(lines, "\n")
    local language = vim.bo.filetype

    vim.ui.input({ prompt = "Refactor instruction: " }, function(instruction)
        if not instruction or instruction == "" then
            return
        end

        vim.notify("[poor-cli] Refactoring...", vim.log.levels.INFO)
        rpc.request("poor-cli/chat", {
            message = "Refactor this " .. language .. " code. Return ONLY the refactored code, no explanations.\n\n"
                .. "Instruction: " .. instruction .. "\n\n"
                .. "```" .. language .. "\n" .. code .. "\n```",
        }, function(result, err)
            vim.schedule(function()
                if err then
                    vim.notify("[poor-cli] Refactor failed: " .. vim.inspect(err), vim.log.levels.ERROR)
                    return
                end

                if result and result.content then
                    local new_code = result.content:gsub("^```[%w]*\n", ""):gsub("\n```$", "")
                    local new_lines = vim.split(new_code, "\n", { plain = true })
                    pcall(vim.cmd, "undojoin")
                    vim.api.nvim_buf_set_lines(0, line1 - 1, line2, false, new_lines)
                    vim.notify("[poor-cli] Refactored! (undo with u)", vim.log.levels.INFO)
                end
            end)
        end)
    end)
end

function M.generate_tests()
    local rpc = require("poor-cli.rpc")

    local node = vim.treesitter.get_node()
    local func_node = nil
    while node do
        local node_type = node:type()
        if node_type:match("function") or node_type:match("method") then
            func_node = node
            break
        end
        node = node:parent()
    end

    local code
    if func_node then
        local start_row, _, end_row, _ = func_node:range()
        local lines = vim.api.nvim_buf_get_lines(0, start_row, end_row + 1, false)
        code = table.concat(lines, "\n")
    else
        vim.cmd("normal! vip")
        vim.cmd('normal! "xy')
        code = vim.fn.getreg("x")
        vim.cmd("normal! \\<Esc>")
    end

    local language = vim.bo.filetype
    local file_path = vim.fn.expand("%:p")
    local buf_lines = vim.api.nvim_buf_get_lines(0, 0, math.min(30, vim.api.nvim_buf_line_count(0)), false)
    local imports = {}
    for _, line in ipairs(buf_lines) do
        if line:match("^import ")
            or line:match("^from ")
            or line:match("^use ")
            or line:match("^require")
            or line:match("^#include")
            or line:match("^const .* = require")
        then
            table.insert(imports, line)
        end
    end
    local imports_ctx = #imports > 0 and ("\nImports:\n" .. table.concat(imports, "\n") .. "\n") or ""

    vim.notify("[poor-cli] Generating tests...", vim.log.levels.INFO)
    rpc.request("poor-cli/chat", {
        message = "Generate unit tests for this " .. language .. " code from " .. file_path .. ".\n"
            .. imports_ctx
            .. "Return ONLY the test code, no explanations.\n\n"
            .. "```" .. language .. "\n" .. code .. "\n```",
    }, function(result, err)
        vim.schedule(function()
            if err then
                vim.notify("[poor-cli] Test generation failed: " .. vim.inspect(err), vim.log.levels.ERROR)
                return
            end

            if result and result.content then
                local config = require("poor-cli.config")
                local base = vim.fn.fnamemodify(file_path, ":t:r")
                local ext = vim.fn.fnamemodify(file_path, ":e")
                local patterns = config.get("test_file_patterns") or {}
                local pattern = patterns[language] or patterns.default or "test_{base}.{ext}"
                local test_name = pattern:gsub("{base}", base):gsub("{ext}", ext)
                vim.cmd("below new " .. test_name)
                vim.bo.filetype = language
                local test_code = result.content:gsub("^```[%w]*\n", ""):gsub("\n```$", "")
                vim.api.nvim_buf_set_lines(0, 0, -1, false, vim.split(test_code, "\n", { plain = true }))
                vim.notify("[poor-cli] Tests generated in " .. test_name, vim.log.levels.INFO)
            end
        end)
    end)
end

function M.generate_docs()
    local rpc = require("poor-cli.rpc")

    local node = vim.treesitter.get_node()
    local func_node = nil
    while node do
        local node_type = node:type()
        if node_type:match("function") or node_type:match("method") then
            func_node = node
            break
        end
        node = node:parent()
    end

    if not func_node then
        vim.notify("[poor-cli] Cursor not in a function", vim.log.levels.WARN)
        return
    end

    local start_row, _, end_row, _ = func_node:range()
    local lines = vim.api.nvim_buf_get_lines(0, start_row, end_row + 1, false)
    local code = table.concat(lines, "\n")
    local language = vim.bo.filetype

    vim.notify("[poor-cli] Generating docs...", vim.log.levels.INFO)
    rpc.request("poor-cli/chat", {
        message = "Generate a docstring/documentation comment for this " .. language .. " function. "
            .. "Return ONLY the docstring, ready to be inserted above the function.\n\n"
            .. "```" .. language .. "\n" .. code .. "\n```",
    }, function(result, err)
        vim.schedule(function()
            if err then
                vim.notify("[poor-cli] Doc generation failed: " .. vim.inspect(err), vim.log.levels.ERROR)
                return
            end

            if result and result.content then
                local docstring = result.content:gsub("^```[%w]*\n", ""):gsub("\n```$", "")
                vim.api.nvim_buf_set_lines(0, start_row, start_row, false, vim.split(docstring, "\n", { plain = true }))
                vim.notify("[poor-cli] Docs generated!", vim.log.levels.INFO)
            end
        end)
    end)
end

return M
