"""
Automated PR review agent for poor-cli.

Fetches PR diffs via `gh` CLI, sends to AI for structured review,
and posts results as PR comments. Supports manual, CI, and webhook triggers.
"""

from __future__ import annotations

import asyncio
import json
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from .exceptions import setup_logger

logger = setup_logger(__name__)

DEFAULT_REVIEW_FOCUS = ["bugs", "security", "performance", "style", "test-coverage"]


@dataclass
class ReviewIssue:
    """Single issue found during review."""
    severity: str # critical | warning | suggestion | info
    file: str
    line: Optional[int]
    message: str
    suggestion: str = ""

    def to_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {
            "severity": self.severity,
            "file": self.file,
            "message": self.message,
        }
        if self.line:
            d["line"] = self.line
        if self.suggestion:
            d["suggestion"] = self.suggestion
        return d

    def to_markdown(self) -> str:
        icon = {"critical": "🔴", "warning": "🟡", "suggestion": "🔵", "info": "ℹ️"}.get(self.severity, "•")
        loc = f"`{self.file}:{self.line}`" if self.line else f"`{self.file}`"
        parts = [f"{icon} **{self.severity.upper()}** in {loc}", self.message]
        if self.suggestion:
            parts.append(f"  > Suggestion: {self.suggestion}")
        return "\n".join(parts)


@dataclass
class ReviewResult:
    """Complete PR review result."""
    pr_number: int
    issues: List[ReviewIssue] = field(default_factory=list)
    summary: str = ""
    files_reviewed: int = 0
    passed: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "prNumber": self.pr_number,
            "issues": [i.to_dict() for i in self.issues],
            "summary": self.summary,
            "filesReviewed": self.files_reviewed,
            "passed": self.passed,
        }

    def to_markdown(self) -> str:
        status = "✅ Passed" if self.passed else "❌ Issues Found"
        parts = [
            f"## PR Review — {status}",
            f"Reviewed {self.files_reviewed} files.",
            "",
        ]
        if self.summary:
            parts.append(self.summary)
            parts.append("")
        if self.issues:
            by_sev: Dict[str, List[ReviewIssue]] = {}
            for issue in self.issues:
                by_sev.setdefault(issue.severity, []).append(issue)
            for sev in ["critical", "warning", "suggestion", "info"]:
                items = by_sev.get(sev, [])
                if items:
                    parts.append(f"### {sev.title()} ({len(items)})")
                    for item in items:
                        parts.append(item.to_markdown())
                    parts.append("")
        parts.append("---\n*Generated by poor-cli review agent*")
        return "\n".join(parts)


def _gh_available() -> bool:
    try:
        subprocess.run(["gh", "--version"], capture_output=True, check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def get_pr_diff(pr_number: int) -> str:
    """Fetch PR diff via gh CLI."""
    result = subprocess.run(
        ["gh", "pr", "diff", str(pr_number)],
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"gh pr diff failed: {result.stderr.strip()}")
    return result.stdout


def get_pr_info(pr_number: int) -> Dict[str, Any]:
    """Fetch PR metadata via gh CLI."""
    result = subprocess.run(
        ["gh", "pr", "view", str(pr_number), "--json",
         "title,body,author,baseRefName,headRefName,files,additions,deletions"],
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        return {"number": pr_number}
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return {"number": pr_number}


def post_review_comment(pr_number: int, body: str) -> bool:
    """Post a review comment on the PR via gh CLI."""
    result = subprocess.run(
        ["gh", "pr", "comment", str(pr_number), "--body", body],
        capture_output=True, text=True, check=False,
    )
    return result.returncode == 0


async def review_pr(
    pr_number: int,
    focus: Optional[List[str]] = None,
    post_comment: bool = False,
    core: Any = None,
) -> ReviewResult:
    """
    Review a PR by fetching its diff and sending to AI for analysis.

    Args:
        pr_number: GitHub PR number.
        focus: Review focus areas (default: bugs, security, performance, style, test-coverage).
        post_comment: If True, post the review as a PR comment.
        core: Optional PoorCLICore instance for AI analysis.
    """
    if not _gh_available():
        raise RuntimeError("gh CLI not available — install from https://cli.github.com")

    diff = get_pr_diff(pr_number)
    info = get_pr_info(pr_number)
    focus_areas = focus or DEFAULT_REVIEW_FOCUS

    # count files from diff headers
    files_changed = diff.count("\ndiff --git ")
    if diff.startswith("diff --git "):
        files_changed += 1

    # build review prompt
    title = info.get("title", f"PR #{pr_number}")
    body = info.get("body", "")
    prompt = _build_review_prompt(pr_number, title, body, diff, focus_areas)

    # if we have a core instance, use AI for analysis
    if core and core.provider:
        issues, summary = await _ai_review(core, prompt)
    else:
        # basic heuristic review without AI
        issues, summary = _heuristic_review(diff, focus_areas)

    has_critical = any(i.severity == "critical" for i in issues)
    result = ReviewResult(
        pr_number=pr_number,
        issues=issues,
        summary=summary,
        files_reviewed=files_changed,
        passed=not has_critical,
    )

    if post_comment:
        md = result.to_markdown()
        post_review_comment(pr_number, md)
        logger.info("posted review comment on PR #%d", pr_number)

    return result


def _build_review_prompt(
    pr_number: int, title: str, body: str, diff: str, focus: List[str]
) -> str:
    # truncate diff if too large
    max_diff = 50000
    if len(diff) > max_diff:
        diff = diff[:max_diff] + "\n\n[diff truncated]"
    return (
        f"Review PR #{pr_number}: {title}\n\n"
        f"Description:\n{body}\n\n"
        f"Focus areas: {', '.join(focus)}\n\n"
        f"For each issue found, output a JSON object on its own line with keys: "
        f"severity (critical|warning|suggestion|info), file, line (nullable), "
        f"message, suggestion.\n\n"
        f"After all issues, output a line starting with SUMMARY: followed by "
        f"a brief overall assessment.\n\n"
        f"Diff:\n```\n{diff}\n```"
    )


async def _ai_review(core: Any, prompt: str) -> tuple[List[ReviewIssue], str]:
    """Use AI to analyze the diff and extract issues."""
    issues: List[ReviewIssue] = []
    accumulated = ""
    try:
        async for event in core.send_message_events(prompt):
            if event.type == "text_chunk":
                accumulated += event.data.get("chunk", "")
            elif event.type == "done":
                break
    except Exception as exc:
        return [], f"AI review failed: {exc}"

    summary = ""
    for line in accumulated.splitlines():
        line = line.strip()
        if line.startswith("SUMMARY:"):
            summary = line[8:].strip()
            continue
        if line.startswith("{"):
            try:
                obj = json.loads(line)
                issues.append(ReviewIssue(
                    severity=obj.get("severity", "info"),
                    file=obj.get("file", ""),
                    line=obj.get("line"),
                    message=obj.get("message", ""),
                    suggestion=obj.get("suggestion", ""),
                ))
            except json.JSONDecodeError:
                pass
    return issues, summary


def _heuristic_review(diff: str, focus: List[str]) -> tuple[List[ReviewIssue], str]:
    """Basic pattern-based review without AI."""
    issues: List[ReviewIssue] = []
    current_file = ""
    line_num = 0

    patterns = {
        "TODO": ("info", "TODO comment found"),
        "FIXME": ("warning", "FIXME comment found"),
        "HACK": ("warning", "HACK comment found"),
        "password": ("critical", "Possible hardcoded password"),
        "secret": ("critical", "Possible hardcoded secret"),
        "api_key": ("critical", "Possible hardcoded API key"),
        "console.log": ("suggestion", "Debug console.log left in code"),
        "print(": ("suggestion", "Debug print statement left in code"),
        "debugger": ("warning", "Debugger statement left in code"),
    }

    for line in diff.splitlines():
        if line.startswith("diff --git"):
            parts = line.split(" b/")
            current_file = parts[-1] if len(parts) > 1 else ""
            line_num = 0
        elif line.startswith("@@"):
            import re
            m = re.search(r'\+(\d+)', line)
            line_num = int(m.group(1)) if m else 0
        elif line.startswith("+") and not line.startswith("+++"):
            line_num += 1
            content = line[1:]
            for pattern, (severity, message) in patterns.items():
                if pattern.lower() in content.lower():
                    issues.append(ReviewIssue(
                        severity=severity,
                        file=current_file,
                        line=line_num,
                        message=message,
                    ))

    summary = f"Heuristic review found {len(issues)} issues."
    return issues, summary
