export type AcraEntityRecord = {
  readonly uen: string;
  readonly issuance_agency_id: string;
  readonly entity_name: string;
  readonly entity_type_description: string;
  readonly business_constitution_description: string;
  readonly company_type_description: string;
  readonly paf_constitution_description: string;
  readonly entity_status_description: string;
  readonly registration_incorporation_date: string;
  readonly uen_issue_date: string;
  readonly address_type: string;
  readonly block: string;
  readonly street_name: string;
  readonly level_no: string;
  readonly unit_no: string;
  readonly building_name: string;
  readonly postal_code: string;
  readonly other_address_line1: string;
  readonly other_address_line2: string;
  readonly account_due_date: string;
  readonly annual_return_date: string;
  readonly primary_ssic_code: string;
  readonly primary_ssic_description: string;
  readonly primary_user_described_activity: string;
  readonly secondary_ssic_code: string;
  readonly secondary_ssic_description: string;
  readonly secondary_user_described_activity: string;
  readonly no_of_officers: string;
};

export type AcraNormalizedEntityRecord = {
  readonly uen: string;
  readonly issuanceAgencyId: string;
  readonly entityName: string;
  readonly entityTypeDescription: string;
  readonly businessConstitutionDescription: string | null;
  readonly companyTypeDescription: string | null;
  readonly pafConstitutionDescription: string | null;
  readonly entityStatusDescription: string;
  readonly registrationIncorporationDate: string;
  readonly uenIssueDate: string;
  readonly addressType: string;
  readonly block: string | null;
  readonly streetName: string | null;
  readonly levelNo: string | null;
  readonly unitNo: string | null;
  readonly buildingName: string | null;
  readonly postalCode: string | null;
  readonly otherAddressLine1: string | null;
  readonly otherAddressLine2: string | null;
  readonly accountDueDate: string | null;
  readonly annualReturnDate: string | null;
  readonly primarySsicCode: string;
  readonly primarySsicDescription: string | null;
  readonly primaryUserDescribedActivity: string | null;
  readonly secondarySsicCode: string | null;
  readonly secondarySsicDescription: string | null;
  readonly secondaryUserDescribedActivity: string | null;
  readonly noOfOfficers: number | null;
};
