import { S } from './state.js';
import { initScene } from './scene.js';
import { initGrid } from './grid.js';
import { initCollision } from './collision.js';
import { initUndo } from './undo.js';
import { initSelection } from './selection.js';
import { initFurniture } from './furniture.js';
import { initWalls } from './walls.js';
import { initSceneList } from './sceneList.js';
import { initCamera, updateFps } from './camera.js';
import { initIO } from './io.js';
import { initShortcuts } from './shortcuts.js';
import { initContextMenu } from './contextmenu.js';
import { initOverlay } from './overlay.js';
import { initMeasure } from './measure.js';
import { initChat } from './chat.js';
import { initCommandPalette } from './commandpalette.js';
initScene();
initGrid();
initCollision();
initUndo();
initSelection();
initFurniture();
initWalls();
initSceneList();
initCamera();
initIO();
initShortcuts();
initContextMenu();
initOverlay();
initMeasure();
initChat();
initCommandPalette();
function animate() {
  requestAnimationFrame(animate);
  updateFps();
  S.orbit.update();
  S.renderer.render(S.scene, S.camera);
}
animate();
