export const SG_RISK_RULES_SCHEMA_VERSION = "sg-risk-rules/v1";
export const SG_RISK_RULES_VERSION = "2026.05";
export const SG_RISK_RULES_LAST_REVIEWED = "2026-05-17";
export const SG_RISK_RULES_SOURCE = "rules/sg-risk-rules.yml";

export const SG_RISK_RULE_CODES = [
  "ENTITY_NOT_ACTIVE",
  "NO_ACRA_MATCH",
  "BUILDER_LICENSE_EXPIRED",
  "CONTRACTOR_EXPIRED",
  "HEALTH_PRODUCT_LICENCE_EXPIRED",
  "CROSS_SOURCE_NAME_DIVERGENCE",
  "PARTIAL_MODULE_COVERAGE",
  "NO_MODULE_MATCHES",
  "MODULE_INPUT_GAP",
] as const;
