package protocol

const (
	MethodInitialize = "initialize"
	MethodShutdown   = "shutdown"

	MethodChat           = "poor-cli/chat"
	MethodChatLegacy     = "chat"
	MethodChatStreaming  = "poor-cli/chatStreaming"
	MethodInlineComplete = "poor-cli/inlineComplete"
	MethodClearHistory   = "poor-cli/clearHistory"
	MethodCancelRequest  = "poor-cli/cancelRequest"

	MethodStreamChunk       = "poor-cli/streamChunk"
	MethodStreamingChunk    = "poor-cli/streamingChunk"
	MethodThinkingChunk     = "poor-cli/thinkingChunk"
	MethodToolEvent         = "poor-cli/toolEvent"
	MethodToolChunk         = "tool.chunk"
	MethodPoorToolChunk     = "poor-cli/toolChunk"
	MethodInlineChunk       = "poor-cli/inlineChunk"
	MethodCostUpdate        = "poor-cli/costUpdate"
	MethodProgress          = "poor-cli/progress"
	MethodPermissionReq     = "poor-cli/permissionReq"
	MethodPermissionRes     = "poor-cli/permissionRes"
	MethodTimelineEvent     = "poor-cli/timelineEvent"
	MethodInitialized       = "poor-cli/initialized"
	MethodProviderChanged   = "poor-cli/providerChanged"
	MethodStageEvent        = "poor-cli/stageEvent"
	MethodEditCommitted     = "poor-cli/editCommitted"
	MethodContextPressure   = "poor-cli/contextPressure"
	MethodEconomyTurnReport = "poor-cli/economyTurnReport"
	MethodPlanReq           = "poor-cli/planReq"
	MethodPlanRes           = "poor-cli/planRes"

	MethodMemberTyping     = "poor-cli/memberTyping"
	MethodSetTyping        = "poor-cli/setTyping"
	MethodQueueUpdated     = "poor-cli/queueUpdated"
	MethodCollabMemberJoin = "poor-cli/collabMemberJoined"
	MethodCollabMemberLeft = "poor-cli/collabMemberLeft"

	MethodListHostMembers   = "poor-cli/listHostMembers"
	MethodListPresence      = "poor-cli/listPresence"
	MethodListRoomQueue     = "poor-cli/listRoomQueue"
	MethodApproveHostMember = "poor-cli/approveHostMember"
	MethodDenyHostMember    = "poor-cli/denyHostMember"
	MethodRemoveHostMember  = "poor-cli/removeHostMember"
	MethodSetHostMemberRole = "poor-cli/setHostMemberRole"
	MethodHandoffHostMember = "poor-cli/handoffHostMember"

	MethodGetProviderInfo    = "poor-cli/getProviderInfo"
	MethodListProviders      = "poor-cli/listProviders"
	MethodListProvidersBare  = "listProviders"
	MethodSwitchProvider     = "poor-cli/switchProvider"
	MethodSwitchProviderBare = "switchProvider"
	MethodSetAPIKey          = "poor-cli/setApiKey"
	MethodSetAPIKeyBare      = "setApiKey"
	MethodGetAPIKeyStatus    = "poor-cli/getApiKeyStatus"
	MethodTestAPIKey         = "poor-cli/testApiKey"
	MethodListOllamaModels   = "poor-cli/listOllamaModels"

	MethodDiffList         = "diff.list"
	MethodListPendingEdits = "poor-cli/listPendingEdits"
	MethodDiffPreview      = "diff.preview"
	MethodPreviewEdit      = "poor-cli/previewEdit"
	MethodDiffStage        = "diff.stage"
	MethodStageEdit        = "poor-cli/stageEdit"
	MethodDiffAccept       = "diff.accept"
	MethodAcceptHunk       = "poor-cli/acceptHunk"
	MethodAcceptAll        = "poor-cli/acceptAll"
	MethodDiffReject       = "diff.reject"
	MethodRejectHunk       = "poor-cli/rejectHunk"
	MethodRejectAll        = "poor-cli/rejectAll"
	MethodDiffRegen        = "diff.regen"
	MethodRegenerateHunk   = "poor-cli/regenerateHunk"
	MethodVoteOnHunk       = "poor-cli/voteOnHunk"
	MethodGetHunkVotes     = "poor-cli/getHunkVotes"
	MethodHunkVoteUpdated  = "poor-cli/hunkVoteUpdated"

	MethodTimelineList    = "timeline.list"
	MethodTimelineCancel  = "timeline.cancel"
	MethodTimelineRetry   = "timeline.retry"
	MethodTimelineDismiss = "timeline.dismiss"

	MethodGetSessionCost         = "poor-cli/getSessionCost"
	MethodCostSummary            = "poor-cli/costSummary"
	MethodCostSnapshot           = "cost.snapshot"
	MethodCostHistory            = "cost.history"
	MethodGetEconomySavings      = "poor-cli/getEconomySavings"
	MethodSavingsSummary         = "poor-cli/savingsSummary"
	MethodSavingsSnapshot        = "savings.snapshot"
	MethodSavingsHistory         = "savings.history"
	MethodSetEconomyPreset       = "poor-cli/setEconomyPreset"
	MethodGetCacheStats          = "poor-cli/getCacheStats"
	MethodClearSemanticCache     = "poor-cli/clearSemanticCache"
	MethodGetContextPressure     = "poor-cli/getContextPressure"
	MethodGetContextBreakdown    = "poor-cli/getContextBreakdown"
	MethodEstimateCost           = "poor-cli/estimateCost"
	MethodCompareModelCost       = "poor-cli/compareModelCost"
	MethodExportCostReport       = "poor-cli/exportCostReport"
	MethodGetTokensVisualization = "poor-cli/getTokensVisualization"
	MethodGetCostHistory         = "poor-cli/getCostHistory"
	MethodApplyBudgetTemplate    = "poor-cli/applyBudgetTemplate"
	MethodListBudgetTemplates    = "poor-cli/listBudgetTemplates"

	MethodListSessions       = "poor-cli/listSessions"
	MethodSwitchSession      = "poor-cli/switchSession"
	MethodListHistory        = "poor-cli/listHistory"
	MethodSearchHistory      = "poor-cli/searchHistory"
	MethodListSkills         = "poor-cli/listSkills"
	MethodGetSkill           = "poor-cli/getSkill"
	MethodListCustomCommands = "poor-cli/listCustomCommands"
	MethodGetCustomCommand   = "poor-cli/getCustomCommand"
	MethodRunCustomCommand   = "poor-cli/runCustomCommand"
	MethodExportConversation = "poor-cli/exportConversation"
	MethodGCCheckpoints      = "poor-cli/gcCheckpoints"
	MethodSaveSession        = "poor-cli/saveSession"
	MethodRestoreSession     = "poor-cli/restoreSession"
	MethodCreateSession      = "poor-cli/createSession"
	MethodDestroySession     = "poor-cli/destroySession"
	MethodForkSession        = "poor-cli/forkSession"
	MethodListMuxSessions    = "poor-cli/listMuxSessions"
	MethodRenameSession      = "poor-cli/renameSession"
	MethodListCheckpoints    = "poor-cli/listCheckpoints"
	MethodCreateCheckpoint   = "poor-cli/createCheckpoint"
	MethodRestoreCheckpoint  = "poor-cli/restoreCheckpoint"
	MethodPreviewCheckpoint  = "poor-cli/previewCheckpoint"

	MethodMcpList            = "mcp.list"
	MethodPoorMcpList        = "poor-cli/mcpList"
	MethodMcpToggle          = "mcp.toggle"
	MethodPoorMcpToggle      = "poor-cli/mcpToggle"
	MethodMcpEdit            = "mcp.edit"
	MethodPoorMcpEdit        = "poor-cli/mcpEdit"
	MethodMcpRemove          = "mcp.remove"
	MethodPoorMcpRemove      = "poor-cli/mcpRemove"
	MethodMcpHealth          = "mcp.health"
	MethodPoorMcpHealth      = "poor-cli/mcpHealth"
	MethodMcpTest            = "mcp.test"
	MethodPoorMcpTest        = "poor-cli/mcpTest"
	MethodMcpRegistrySearch  = "mcp.registry.search"
	MethodRegistrySearch     = "registrySearch"
	MethodPoorRegistrySearch = "poor-cli/registrySearch"
	MethodToolStreamAck      = "poor-cli/toolStreamAck"
	MethodCancelTool         = "poor-cli/cancelTool"

	MethodContextEngine  = "context.engine"
	MethodContextExplain = "context.explain"
	MethodContextStatus  = "poor-cli/contextStatus"
	MethodWatchStatus    = "watch.status"
)
