const ALIAS_MAP: Readonly<Record<string, string>> = {
  "macro brief": "sg_macro_brief",
  "economic brief": "sg_macro_brief",
  "business dossier": "sg_business_dossier",
  "company dossier": "sg_business_dossier",
  "property brief": "sg_property_brief",
  "location brief": "sg_property_brief",
  "transport brief": "sg_transport_brief",
  "transport snapshot": "sg_transport_brief",
  "transport status": "sg_transport_brief",
  "environment brief": "sg_environment_brief",
  "environment snapshot": "sg_environment_brief",
  forex: "sg_mas_exchange_rates",
  "exchange rate": "sg_mas_exchange_rates",
  currency: "sg_mas_exchange_rates",
  sora: "sg_mas_interest_rates",
  "interest rate": "sg_mas_interest_rates",
  "lending rate": "sg_mas_interest_rates",
  gdp: "sg_singstat_search",
  cpi: "sg_singstat_search",
  inflation: "sg_singstat_search",
  unemployment: "sg_singstat_search",
  trade: "sg_singstat_search",
  "singstat table": "sg_singstat_table",
  "time series": "sg_singstat_timeseries",
  timeseries: "sg_singstat_timeseries",
  "singstat browse": "sg_singstat_browse",
  "singstat categories": "sg_singstat_browse",
  population: "sg_onemap_population",
  demographic: "sg_onemap_population",
  "age group": "sg_onemap_population",
  income: "sg_onemap_population",
  geocode: "sg_onemap_geocode",
  "reverse geocode": "sg_onemap_reverse_geocode",
  "address from coordinates": "sg_onemap_reverse_geocode",
  "postal code": "sg_onemap_geocode",
  address: "sg_onemap_geocode",
  "where is": "sg_onemap_geocode",
  directions: "sg_onemap_route",
  route: "sg_onemap_route",
  "how to get": "sg_onemap_route",
  "coordinate conversion": "sg_onemap_convert_coords",
  "convert coordinates": "sg_onemap_convert_coords",
  svy21: "sg_onemap_convert_coords",
  wgs84: "sg_onemap_convert_coords",
  property: "sg_ura_property_transactions",
  resale: "sg_ura_property_transactions",
  rental: "sg_ura_property_transactions",
  condo: "sg_ura_property_transactions",
  condominium: "sg_ura_property_transactions",
  "development charge": "sg_ura_dev_charges",
  "dev charge": "sg_ura_dev_charges",
  zoning: "sg_ura_planning_area",
  "plot ratio": "sg_ura_planning_area",
  "master plan": "sg_ura_planning_area",
  hdb: "sg_hdb_resale_prices",
  "flat prices": "sg_hdb_resale_prices",
  "resale prices": "sg_hdb_resale_prices",
  "rental prices": "sg_hdb_rental_prices",
  "bus arrival": "sg_lta_bus_arrivals",
  "train alert": "sg_lta_train_alerts",
  "traffic incident": "sg_lta_traffic_incidents",
  forecast: "sg_nea_forecast_2hr",
  weather: "sg_nea_forecast_2hr",
  rainfall: "sg_nea_rainfall",
  "air quality": "sg_nea_air_quality",
  pm25: "sg_nea_air_quality",
  psi: "sg_nea_air_quality",
  salesperson: "sg_cea_salespersons",
  "estate agent": "sg_cea_salespersons",
  cea: "sg_cea_salespersons",
  "licensed builder": "sg_bca_licensed_builders",
  "registered contractor": "sg_bca_registered_contractors",
  "builder class": "sg_bca_licensed_builders",
  workhead: "sg_bca_registered_contractors",
  bca: "sg_bca_registered_contractors",
  architect: "sg_boa_architects",
  architects: "sg_boa_architects",
  "architecture firm": "sg_boa_architecture_firms",
  boa: "sg_boa_architecture_firms",
  acra: "sg_acra_entities",
  uen: "sg_acra_entities",
  "company registration": "sg_acra_entities",
  "corporate entity": "sg_acra_entities",
  pharmacy: "sg_hsa_licensed_pharmacies",
  pharmacies: "sg_hsa_licensed_pharmacies",
  "health product": "sg_hsa_health_product_licensees",
  "health products": "sg_hsa_health_product_licensees",
  hsa: "sg_hsa_health_product_licensees",
  hotel: "sg_hlb_hotels",
  hotels: "sg_hlb_hotels",
  hlb: "sg_hlb_hotels",
  keeper: "sg_hlb_hotels",
  "browse collections": "sg_datagov_browse",
  collection: "sg_datagov_browse",
  "dataset resources": "sg_datagov_resources",
  "dataset rows": "sg_datagov_rows",
  columns: "sg_datagov_resources",
  "moe schools": "sg_moe_schools",
  "school directory": "sg_moe_schools",
  "school lookup": "sg_moe_schools",
  "moh facilities": "sg_moh_facilities",
  "healthcare facilities": "sg_moh_facilities",
  "hospital directory": "sg_moh_facilities",
  "clinic directory": "sg_moh_facilities",
  hawker: "sg_datagov_search",
  school: "sg_datagov_search",
  park: "sg_datagov_search",
  "community club": "sg_pa_community_outlets",
  "passion wave": "sg_pa_community_outlets",
  "resident network": "sg_pa_resident_network_centres",
  "residents network": "sg_pa_resident_network_centres",
  "resident committee": "sg_pa_resident_network_centres",
  childcare: "sg_ecda_childcare_centres",
  preschool: "sg_ecda_childcare_centres",
  kindergarten: "sg_ecda_childcare_centres",
  "family service centre": "sg_msf_family_services",
  "family service centers": "sg_msf_family_services",
  "student care": "sg_msf_student_care_services",
  scfa: "sg_msf_student_care_services",
  "social service office": "sg_msf_social_service_offices",
  sportsg: "sg_sportsg_facilities",
  "sports facility": "sg_sportsg_facilities",
};

export const resolveAlias = (term: string): string | null => {
  const lower = term.toLowerCase();

  const exact = ALIAS_MAP[lower];
  if (exact !== undefined) return exact;

  for (const [alias, tool] of Object.entries(ALIAS_MAP)) {
    if (lower.includes(alias)) return tool;
  }

  return null;
};
